export default {
  button: "Button",
  input: "Input",
  textarea: "Textarea",
  card: "Card",
  badge: "Badge",
  checkbox: "Checkbox",
  "radio-group": "Radio Group",
  toggle: "Toggle",
  toast: "Toast",
  accordion: "Accordion",
  modal: "Modal",
  dropdown: "Dropdown",
  tabs: "Tabs",
  breadcrumb: "Breadcrumb",
  tooltip: "Tooltip",
  popover: "Popover",
  table: "Table",
};
